import type { NextPage } from 'next'
import classes from 'src/pages/Home.module.sass'
import back from '@images/back.jpg'
import MainBack from "@components/MainBack/MainBack";


const Home: NextPage = () => {
   return (
      <div className={classes.container}>
         <MainBack
            title={'Main/ Как говориться сложно срать стоя на руках и не испачкать спину'}
            imageSrc={back.src}
         />
         
         <div className={classes.wrapper}>
            <span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet architecto asperiores, cum eius eveniet ipsum maxime mollitia nesciunt nostrum officia quae quaerat quidem, quo quos rem reprehenderit, repudiandae rerum temporibus.</span><span>Amet dolor dolores ipsam natus nemo nisi porro quas rem rerum voluptate. Ab animi commodi dignissimos dolor harum, in, libero magnam minus molestias necessitatibus neque nobis quam quas, suscipit veritatis.</span><span>Ab adipisci animi, deleniti dignissimos dolore ducimus et excepturi explicabo facere hic, ipsum necessitatibus nesciunt numquam obcaecati quibusdam, rem repellat rerum tempore tenetur voluptate. Ab esse laboriosam porro. Quae, ut.</span><span>Doloremque doloribus eveniet fugit ipsum mollitia. Accusamus, aspernatur beatae, debitis deserunt ducimus eligendi expedita facilis hic maiores maxime minima numquam odio officia rem repellat sequi soluta tempora, ullam veniam vero!</span><span>A adipisci cupiditate, debitis in libero minus omnis quasi quibusdam quis quod reprehenderit temporibus totam vero? Dolore in ipsum laborum molestiae omnis quis quisquam ratione, saepe tempora temporibus veritatis voluptatum?</span><span>Odit, officiis, repellendus! Animi architecto enim, exercitationem hic necessitatibus nisi non praesentium quas! Animi, debitis dolor doloribus dolorum eligendi esse eveniet ex fugit numquam officia quod tempora tempore ullam voluptatibus.</span><span>Consequuntur ducimus eum fuga fugit laborum natus perferendis quas recusandae repellat repudiandae? A, dignissimos dolor labore libero minima nihil obcaecati odio optio perferendis possimus ratione rem sapiente temporibus totam, veniam?</span><span>Accusamus aspernatur atque culpa eum, expedita minus necessitatibus, nobis numquam, perspiciatis repudiandae sed similique soluta. Ad assumenda blanditiis corporis sapiente. Cumque dolores dolorum modi nam natus numquam, provident voluptatem voluptatum.</span></span>
            <span><span>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet architecto asperiores, cum eius eveniet ipsum maxime mollitia nesciunt nostrum officia quae quaerat quidem, quo quos rem reprehenderit, repudiandae rerum temporibus.</span><span>Amet dolor dolores ipsam natus nemo nisi porro quas rem rerum voluptate. Ab animi commodi dignissimos dolor harum, in, libero magnam minus molestias necessitatibus neque nobis quam quas, suscipit veritatis.</span><span>Ab adipisci animi, deleniti dignissimos dolore ducimus et excepturi explicabo facere hic, ipsum necessitatibus nesciunt numquam obcaecati quibusdam, rem repellat rerum tempore tenetur voluptate. Ab esse laboriosam porro. Quae, ut.</span><span>Doloremque doloribus eveniet fugit ipsum mollitia. Accusamus, aspernatur beatae, debitis deserunt ducimus eligendi expedita facilis hic maiores maxime minima numquam odio officia rem repellat sequi soluta tempora, ullam veniam vero!</span><span>A adipisci cupiditate, debitis in libero minus omnis quasi quibusdam quis quod reprehenderit temporibus totam vero? Dolore in ipsum laborum molestiae omnis quis quisquam ratione, saepe tempora temporibus veritatis voluptatum?</span><span>Odit, officiis, repellendus! Animi architecto enim, exercitationem hic necessitatibus nisi non praesentium quas! Animi, debitis dolor doloribus dolorum eligendi esse eveniet ex fugit numquam officia quod tempora tempore ullam voluptatibus.</span><span>Consequuntur ducimus eum fuga fugit laborum natus perferendis quas recusandae repellat repudiandae? A, dignissimos dolor labore libero minima nihil obcaecati odio optio perferendis possimus ratione rem sapiente temporibus totam, veniam?</span><span>Accusamus aspernatur atque culpa eum, expedita minus necessitatibus, nobis numquam, perspiciatis repudiandae sed similique soluta. Ad assumenda blanditiis corporis sapiente. Cumque dolores dolorum modi nam natus numquam, provident voluptatem voluptatum.</span></span>
         </div>
      </div>
   )
}

export default Home